---
title: "Study 2 Example Report"
---

Most Recent Update: `r Sys.time()`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

Remember that a general outline and set of instructions for the Study 2 report [is available here](study2b.html).

## The Study 2 Example Report

In the [Study 2 Example Report](https://github.com/THOMASELOVE/431-projectB-samples), I demonstrate many (but not all) of the elements you would need to complete in Study 2, including:

- data ingest
- cleaning the data, as well as
- building a codebook for the final variables and describing them numerically, plus
- partitioning the data
- considering (and applying) a transformation
- fitting and summarizing a big model and a small model
- comparing the two models within the training sample
- validating and comparing the two models within the holdout (test) sample

for a simulated data set containing information on 999 subjects about high blood pressure control.

## Study 2 Example Report: The Files

- The R Markdown file [can be downloaded here](https://github.com/THOMASELOVE/431-projectB-samples/blob/main/431-projB-sample-study2.Rmd).
- The HTML result [can be viewed here](https://rpubs.com/TELOVE/projectB-431-sample-study2).

The data file for the Study 2 Example Report is described in the R Markdown and HTML files above and is found on [the 431-data website](https://github.com/THOMASELOVE/431-data). It is called:

- **hbp_study.csv** (999 observations in 12 columns)

The subjects are identified with a code called `subj_id` 
 
## Caveats

1. The Study 2 Example Report does not precisely follow the requirements from Study 2 for certain sections, because that is a big part of your job. 

2. In the Study 2 Example Report, I don't make much of an effort to make attractive graphs. You really should.

3. Outside of those caveats, the Study 2 Example Report is meant to be accurate and reflect the level of detail I'm looking for, although it is certainly possible to expand on these demonstrations in your work, if that seems helpful. I believe the Study 2 Example Report documents to be largely accurate, but many eyes will find some issues, eventually. 

If people find corrections and would be good enough to post them to Campuswire (under the projectB folder, please) I will attempt to reflect those edits in revisions. If I do something in the demonstration project that appears to be in conflict with the instructions for Study 2, then (a) please let me know, and (b) treat the Study 2 instructions as your guidepost in completing your work.


